theme: jekyll-theme-minimal
title: Nitish Patkar
description: 
logo: images/portrait.jpg

# Custom links
github_url: https://github.com/nitishspatkar
orcid_url: https://orcid.org/0000-0001-8084-4980
linkedin_url: https://www.linkedin.com/in/nitishpatkar/

